# Generated by Django 3.2.5 on 2021-07-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=64)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('radiation', models.CharField(max_length=256)),
                ('gamma', models.CharField(max_length=256)),
                ('age_of_sample', models.IntegerField()),
            ],
        ),
    ]
