# Generated by Django 3.2.6 on 2021-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumi', '0004_auto_20210821_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to='lumi.LoginSystem'),
        ),
    ]
