# Generated by Django 3.2.5 on 2021-08-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumi', '0006_auto_20210826_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='Etch_depth_max_μm',
            new_name='Etch_depth_max_um',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='Etch_depth_min_μm',
            new_name='Etch_depth_min_um',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='Grain_size_max_μm',
            new_name='Grain_size_max_um',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='Grain_size_min_μm',
            new_name='Grain_size_min_um',
        ),
    ]
