# Generated by Django 3.2.5 on 2021-08-31 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumi', '0007_auto_20210831_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='sample_ID',
            new_name='sample_name',
        ),
    ]
