# Generated by Django 3.2.5 on 2021-09-01 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lumi', '0010_alter_project_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
