# Generated by Django 3.2.5 on 2021-09-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumi', '0011_auto_20210901_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='created_by',
            field=models.CharField(default='', max_length=64),
        ),
    ]
