# Generated by Django 3.2.5 on 2021-09-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumi', '0013_auto_20210909_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='Grain_size_max_um',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='Grain_size_min_um',
            field=models.FloatField(null=True),
        ),
    ]
